name: bloodhero
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Para la gesti칩n de estado (recomendado)
  flutter_riverpod: ^3.0.3
  
  # Para la navegaci칩n entre pantallas
  go_router: ^17.0.0

  # Para los puntos indicadores en el Onboarding
  smooth_page_indicator: ^1.1.0

  # Para usar fuentes de Google f치cilmente
  google_fonts: ^6.2.1

  #Mapa
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  flutter_map_marker_cluster: ^8.2.2
  url_launcher: ^6.3.0

  # Compartir logros y contenido
  share_plus: ^12.0.1

  # Dependencias de Firebase:
  firebase_core: ^4.2.1   # Necesario para inicializar Firebase
  firebase_auth: ^6.1.2   # Para la autenticaci칩n (login, registro)
  cloud_firestore: ^6.1.0 # Para la base de datos Firestore

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/images/
  - assets/screen/
  - assets/images/centers/