name: bloodhero
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Para la gestión de estado (recomendado)
  flutter_riverpod: ^3.0.3
  
  # Para la navegación entre pantallas
  go_router: ^16.2.4

  # Para los puntos indicadores en el Onboarding
  smooth_page_indicator: ^1.1.0

  # Para usar fuentes de Google fácilmente
  google_fonts: ^6.2.1

  # Mapas basados en OpenStreetMap
  flutter_map: ^8.2.2
  latlong2: ^0.9.0

  # Compartir logros y contenido
  share_plus: ^12.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/images/
  - assets/screen/
